# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import planner_pb2 as planner__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in planner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlannerServiceStub(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdatePointCloud = channel.unary_unary(
                '/planner_service.PlannerService/UpdatePointCloud',
                request_serializer=planner__pb2.UpdatePointCloudRequest.SerializeToString,
                response_deserializer=planner__pb2.UpdatePointCloudResponse.FromString,
                _registered_method=True)
        self.ConvertToMesh = channel.unary_unary(
                '/planner_service.PlannerService/ConvertToMesh',
                request_serializer=planner__pb2.ConvertToMeshRequest.SerializeToString,
                response_deserializer=planner__pb2.ConvertToMeshResponse.FromString,
                _registered_method=True)
        self.GetClosestPoint = channel.unary_unary(
                '/planner_service.PlannerService/GetClosestPoint',
                request_serializer=planner__pb2.GetClosestPointRequest.SerializeToString,
                response_deserializer=planner__pb2.GetClosestPointResponse.FromString,
                _registered_method=True)
        self.PlanTrajectory = channel.unary_unary(
                '/planner_service.PlannerService/PlanTrajectory',
                request_serializer=planner__pb2.PlanTrajectoryRequest.SerializeToString,
                response_deserializer=planner__pb2.PlanTrajectoryResponse.FromString,
                _registered_method=True)


class PlannerServiceServicer(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    def UpdatePointCloud(self, request, context):
        """Interface 1: Update point cloud data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertToMesh(self, request, context):
        """Interface 2: Convert fitted surface to mesh triangles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClosestPoint(self, request, context):
        """Interface 3: Get closest point on surface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanTrajectory(self, request, context):
        """Interface 4: Plan trajectory on surface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlannerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdatePointCloud': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePointCloud,
                    request_deserializer=planner__pb2.UpdatePointCloudRequest.FromString,
                    response_serializer=planner__pb2.UpdatePointCloudResponse.SerializeToString,
            ),
            'ConvertToMesh': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertToMesh,
                    request_deserializer=planner__pb2.ConvertToMeshRequest.FromString,
                    response_serializer=planner__pb2.ConvertToMeshResponse.SerializeToString,
            ),
            'GetClosestPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClosestPoint,
                    request_deserializer=planner__pb2.GetClosestPointRequest.FromString,
                    response_serializer=planner__pb2.GetClosestPointResponse.SerializeToString,
            ),
            'PlanTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanTrajectory,
                    request_deserializer=planner__pb2.PlanTrajectoryRequest.FromString,
                    response_serializer=planner__pb2.PlanTrajectoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'planner_service.PlannerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('planner_service.PlannerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlannerService(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    @staticmethod
    def UpdatePointCloud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/planner_service.PlannerService/UpdatePointCloud',
            planner__pb2.UpdatePointCloudRequest.SerializeToString,
            planner__pb2.UpdatePointCloudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertToMesh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/planner_service.PlannerService/ConvertToMesh',
            planner__pb2.ConvertToMeshRequest.SerializeToString,
            planner__pb2.ConvertToMeshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClosestPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/planner_service.PlannerService/GetClosestPoint',
            planner__pb2.GetClosestPointRequest.SerializeToString,
            planner__pb2.GetClosestPointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/planner_service.PlannerService/PlanTrajectory',
            planner__pb2.PlanTrajectoryRequest.SerializeToString,
            planner__pb2.PlanTrajectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
